- name: check if /root/.my.cnf exists
  stat: path=/root/.my.cnf
  register: mycnf
- name: change root password
  mysql_user: user="root" password="{{ mysql_root_password }}"
  when: mysql_root_password is defined and ( mycnf.stat.exists is not defined or not mycnf.stat.exists)
- name: create /root/.my.cnf
  template: src="my.cnf.j2" dest="/root/.my.cnf" owner="root" group="root" mode=0600
  when: mysql_root_password is defined
